---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infrastructure/ha-data
  - ../../apps/weltgewebe/migration/ha
  - ../../apps/weltgewebe/overlays/ha
  - ../../infrastructure/gateway
