import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { computeBuildArtifactTree } from "./build-artifact-evidence.mjs";

const args = process.argv.slice(2);
const allowedArgs = ["--client", "--server"];
const unknownArgs = args.filter((a) => !allowedArgs.includes(a));

if (unknownArgs.length > 0) {
  console.error(`ERROR: Unknown arguments: ${unknownArgs.join(", ")}`);
  console.error(`Usage: node generate-version.js [--client] [--server]`);
  process.exit(1);
}

const writeClient = args.length === 0 || args.includes("--client");
const writeServer = args.length === 0 || args.includes("--server");

const buildDir = path.resolve(process.cwd(), "build");
const targetFile = path.join(buildDir, "_app/version.json");
const targetDir = path.dirname(targetFile);
const clientDir = path.resolve(process.cwd(), "src/lib/generated");
const clientFile = path.join(clientDir, "buildVersion.json");
const clientModuleFile = path.join(clientDir, "buildVersion.ts");

let commit = null;
const suppliedCommit = process.env.GIT_COMMIT_SHA?.trim();
if (suppliedCommit) {
  if (!/^[0-9a-f]{40}$/.test(suppliedCommit)) {
    console.error(
      "ERROR: GIT_COMMIT_SHA must be a full 40-character lowercase hexadecimal commit.",
    );
    process.exit(1);
  }
  commit = suppliedCommit;
} else {
  try {
    const resolvedCommit = execSync("git rev-parse HEAD", {
      encoding: "utf8",
    }).trim();
    if (!/^[0-9a-f]{40}$/.test(resolvedCommit)) {
      throw new Error("git returned a non-canonical commit identity");
    }
    commit = resolvedCommit;
  } catch {
    console.warn(
      "WARNING: Could not determine git commit. Using non-deterministic fallback.",
    );
  }
}
const shortSha = commit?.slice(0, 8) ?? null;

let now = new Date();
if (process.env.SOURCE_DATE_EPOCH) {
  if (!/^[0-9]+$/.test(process.env.SOURCE_DATE_EPOCH)) {
    console.error("ERROR: SOURCE_DATE_EPOCH must be a non-negative integer.");
    process.exit(1);
  }
  const epoch = Number.parseInt(process.env.SOURCE_DATE_EPOCH, 10);
  now = new Date(epoch * 1000);
  if (Number.isNaN(now.getTime())) {
    console.error(
      "ERROR: SOURCE_DATE_EPOCH is outside the supported date range.",
    );
    process.exit(1);
  }
}
const epochMs = now.getTime();
const builtAt = now.toISOString();
const version = shortSha || commit || "unknown";
const buildId = shortSha ? `${shortSha}-${epochMs}` : `unknown-${epochMs}`;
const payload = { version, build_id: buildId, built_at: builtAt };
if (commit) payload.commit = commit;

const filesWritten = [];
if (writeServer) {
  if (!commit) {
    console.error(
      "ERROR: Server build identity requires a canonical Git commit.",
    );
    process.exit(1);
  }
  const artifactTree = computeBuildArtifactTree(buildDir);
  const serverPayload = {
    ...payload,
    artifact_tree: {
      schema_version: artifactTree.schemaVersion,
      sha256: artifactTree.sha256,
      file_count: artifactTree.fileCount,
    },
  };
  fs.mkdirSync(targetDir, { recursive: true });
  fs.writeFileSync(
    targetFile,
    JSON.stringify(serverPayload, null, 2) + "\n",
    "utf8",
  );
  filesWritten.push(targetFile);
}
if (writeClient) {
  fs.mkdirSync(clientDir, { recursive: true });
  fs.writeFileSync(clientFile, JSON.stringify(payload, null, 2) + "\n", "utf8");
  const moduleSource =
    "// AUTO-GENERATED by scripts/generate-version.js — do not edit.\n" +
    "export const BUILD_VERSION = " +
    JSON.stringify(version) +
    " as const;\n" +
    "export default " +
    JSON.stringify(payload, null, 2) +
    " as const;\n";
  fs.writeFileSync(clientModuleFile, moduleSource, "utf8");
  filesWritten.push(clientFile, clientModuleFile);
}
console.log(
  filesWritten.length > 0
    ? `Generated build identity: ${version} at ${filesWritten.join(" and ")}`
    : "No version files written.",
);
