---
services:
  api:
    # erzwingt, dass relative Pfade wie "policies/limits.yaml" unter /app auflösen
    working_dir: /app
    ports:
      - "8081:8080"
    environment:
      # falls die App eine NATS_URL kennt, ist das der Standard
      - NATS_URL=nats://nats:4222
    volumes:
      - ./policies:/app/policies:ro

  nats:
    image: nats:2@sha256:7ff2e641c33dbdb0dd13a943ba0b70d841b71275c607baa53ef9b8661f0b2d8c
    command: ["-js"]
    restart: unless-stopped
    ports:
      - "4222:4222"
