---
services:
  api:
    environment:
      GEWEBE_SEED_DEMO: "true"

  caddy:
    networks:
      - default
      - heimnet
    volumes:
      # Preserve persistent state from base compose (CA/certs/config state)
      # Explicitly listed here to ensure stability across Compose versions
      - caddy_data:/data
      - caddy_config:/config

      # Heimserver-mode: use reference config as primary Caddyfile
      # This replaces the mount from compose.prod.yml (target path match)
      - ../../docs/reference/caddy.heimserver.caddy:/etc/caddy/Caddyfile:ro

networks:
  heimnet:
    external: true
