---
services:
  api:
    # Deliberate Heimserver layout assumption: .env must exist at this absolute path.
    # This injects all variables from the host's .env into the container runtime.
    env_file:
      - /opt/weltgewebe/.env
    ports:
      - 127.0.0.1:8081:8080
    environment:
      NATS_URL: nats://nats:4222
      POLICY_LIMITS_PATH: /app/policies/limits.yaml
      APP_BASE_URL: https://weltgewebe.home.arpa
      AUTH_PUBLIC_LOGIN: '1'
      AUTH_LOG_MAGIC_TOKEN: '0'
      AUTH_AUTO_PROVISION: '1'
      # Open Registration (Option C) requires strict rate limits
      AUTH_ALLOW_EMAILS: ""
      AUTH_RL_IP_PER_MIN: "5"
      AUTH_RL_IP_PER_HOUR: "30"
      AUTH_RL_EMAIL_PER_MIN: "2"
      AUTH_RL_EMAIL_PER_HOUR: "10"
      WEB_UPSTREAM_HOST: weltgewebe.home.arpa
      WEB_UPSTREAM_URL: https://weltgewebe.home.arpa
    volumes:
      - type: bind
        source: /opt/weltgewebe/policies/limits.yaml
        target: /app/policies/limits.yaml
        read_only: true
  nats:
    image: nats:2.10
    command:
      - -js
    restart: always
    volumes:
      - nats_js:/data
  caddy:
    environment: {}
    ports: []
volumes:
  nats_js: null
