---
services:
  api:
    environment:
      GEWEBE_SEED_DEMO: "true"

  caddy:
    networks:
      - default
      - heimnet
    volumes:
      # Use the reference Caddyfile as the main config when running in Heimserver mode.
      - ../../docs/reference/caddy.heimserver.caddy:/etc/caddy/Caddyfile:ro

networks:
  heimnet:
    external: true
