---
services:
  api:
    environment:
      GEWEBE_SEED_DEMO: "true"

  caddy:
    networks:
      - default
      - heimnet
    volumes:
      - ../caddy/Caddyfile.heimserver:/etc/caddy/heimserver/leitstand.caddy:ro

networks:
  heimnet:
    external: true
