services:
  api:
    ports:
    - 127.0.0.1:8081:8080
    environment:
      NATS_URL: nats://nats:4222
      POLICY_LIMITS_PATH: /app/policies/limits.yaml
      APP_BASE_URL: https://weltgewebe.pages.dev
      AUTH_PUBLIC_LOGIN: '1'
      AUTH_LOG_MAGIC_TOKEN: '1'
      AUTH_AUTO_PROVISION: '1'
      AUTH_ALLOW_EMAILS: alexdermohr@gmail.com
    volumes:
    - type: bind
      source: /opt/weltgewebe/policies/limits.yaml
      target: /app/policies/limits.yaml
      read_only: true
  nats:
    image: nats:2.10
    command:
    - -js
    restart: always
    volumes:
    - nats_js:/data
  caddy:
    environment:
      WEB_UPSTREAM_HOST: weltgewebe.pages.dev
      WEB_UPSTREAM_URL: https://weltgewebe.pages.dev
volumes:
  nats_js: null
