---
apiVersion: v1
kind: Namespace
metadata:
  name: weltgewebe-ci
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    weltgewebe.net/data-client: "true"
