---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: weltgewebe-data
resources:
  - namespace.yaml
  - object-store.yaml
  - barman-object-store.yaml
  - postgres-image-catalog.yaml
  - postgres.yaml
  - nats.yaml
