---
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: weltgewebe-postgres
spec:
  images:
    - major: 16
      image: >-
        ghcr.io/cloudnative-pg/postgresql:16.14@sha256:05eae7037dc6a7077cc3fc91a65fe023279060572a237d11aa83e11179443ad1
