---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fixture-config-map.yaml
  - namespace.yaml
  - postgres.yaml
  - nats.yaml
  - network-policy.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: weltgewebe
      app.kubernetes.io/managed-by: flux
