name: cost-report
permissions:
  contents: read
on:
  workflow_dispatch:
  schedule:
    - cron: "7 3 1 * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python tools/py/cost/report.py
      - uses: actions/upload-artifact@v4
        with:
          name: cost-report
          path: docs/reports/cost-report.md
